# Generated by Django 3.2.7 on 2021-09-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('small_image', models.ImageField(upload_to=None)),
                ('large_image', models.ImageField(upload_to=None)),
                ('text', models.TextField()),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
